<a href="https://colab.research.google.com/github/Vulture-hash/RNN_architecture/blob/main/RNN_Architecture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from keras import Sequential
from keras.layers import SimpleRNN, Dense, Input

In [ ]:
model = Sequential()
model.add(SimpleRNN(3, input_shape=(4, 5)))
model.add(Dense(1, activation="sigmoid"))

model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)             │ (None, 3)                   │              27 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
print(model.get_weights()[0].shape)
model.get_weights()[0]

(5, 3)


array([[-0.82156974,  0.10850549, -0.84694177],
       [ 0.8521283 , -0.05287141, -0.70939803],
       [ 0.5966943 , -0.24606097,  0.326495  ],
       [-0.7977494 ,  0.12181848,  0.8350008 ],
       [ 0.57830924, -0.4832629 ,  0.18474287]], dtype=float32)

In [ ]:
print(model.get_weights()[1].shape)
model.get_weights()[1]

(3, 3)


array([[-0.5741763 , -0.07746105,  0.8150591 ],
       [-0.8118486 , -0.07494865, -0.5790376 ],
       [ 0.10594043, -0.9941743 , -0.0198529 ]], dtype=float32)

In [ ]:
print(model.get_weights()[2].shape)
model.get_weights()[2]

(3,)


array([0., 0., 0.], dtype=float32)

In [ ]:
import numpy as np
docs = [
    "I love pizza",               # 3 words
    "He eats apples",             # 3 words
    "She likes coding a lot",     # 5 words
    "We play football outside",   # 4 words
    "They watch movies at night"  # 5 words
]

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token="<OOV>")

In [ ]:
tokenizer.fit_on_texts(docs)

In [ ]:
# tokenizer.word_index

In [ ]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[2, 3, 4],
 [5, 6, 7],
 [8, 9, 10, 11, 12],
 [13, 14, 15, 16],
 [17, 18, 19, 20, 21]]

In [ ]:
from tensorflow.keras.utils import pad_sequences
sequences = pad_sequences(sequences, padding='post')

array([[ 2,  3,  4,  0,  0],
       [ 5,  6,  7,  0,  0],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16,  0],
       [17, 18, 19, 20, 21]], dtype=int32)

In [5]:
# !pip install tensorflow

In [1]:
from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense, Flatten, Embedding, Input
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences

In [2]:
(X_train, y_train), (X_test, y_test) = imdb.load_data()
X_train = pad_sequences(X_train, padding='post')
X_test = pad_sequences(X_test, padding='post')
vocab_size=max([max(seq) for seq in X_train])+1
max_len = X_train.shape[1]

model = Sequential([
    Input(shape=(max_len,)),
    Embedding(input_dim=vocab_size, output_dim=32),
    SimpleRNN(32, return_sequences=False),
    Dense(1, activation='sigmoid')
])

model.compile( optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=7, validation_data=(X_test, y_test))
model.summary()


17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Epoch 1/7
782/782 ━━━━━━━━━━━━━━━━━━━━ 161s 202ms/step - accuracy: 0.4885 - loss: 0.6943 - val_accuracy: 0.5000 - val_loss: 0.6935
Epoch 2/7
782/782 ━━━━━━━━━━━━━━━━━━━━ 198s 199ms/step - accuracy: 0.4993 - loss: 0.6938 - val_accuracy: 0.5000 - val_loss: 0.6953
Epoch 3/7
782/782 ━━━━━━━━━━━━━━━━━━━━ 202s 199ms/step - accuracy: 0.4960 - loss: 0.6938 - val_accuracy: 0.5000 - val_loss: 0.6931
Epoch 4/7
782/782 ━━━━━━━━━━━━━━━━━━━━ 189s 182ms/step - accuracy: 0.4977 - loss: 0.6936 - val_accuracy: 0.5000 - val_loss: 0.6932
Epoch 5/7
782/782 ━━━━━━━━━━━━━━━━━━━━ 202s 182ms/step - accuracy: 0.4966 - loss: 0.6936 - val_accuracy: 0.5000 - val_loss: 0.6932
Epoch 6/7
782/782 ━━━━━━━━━━━━━━━━━━━━ 215s 199ms/step - accuracy: 0.4992 - loss: 0.6936 - val_accuracy: 0.5000 - val_loss: 0.6934
Epoch 7/7
782/782 ━━━━━━━━━━━━━━━━━━━━ 202s 198ms/step - accuracy: 0.4969 - loss: 0.6938 - val_accuracy: 0.5000 - val_loss: 0.6949


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 2494, 32)            │       2,834,784 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn (SimpleRNN)               │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 8,510,693 (32.47 MB)

 Trainable params: 2,836,897 (10.82 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 5,673,796 (21.64 MB)

In [3]:
model.predict(X_test)


782/782 ━━━━━━━━━━━━━━━━━━━━ 29s 36ms/step


array([[0.52955693],
       [0.52955693],
       [0.5295569 ],
       ...,
       [0.5295569 ],
       [0.5295569 ],
       [0.5295569 ]], dtype=float32)